In [ ]:

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/CARS/tabular_data.csv', index_col=0)

In [ ]:
# Python code to preprocess every column of a DataFrame by replacing NaNs with the mean of the column
import pandas as pd
from sklearn.impute import SimpleImputer
# Assuming 'df' is your DataFrame
# df = pd.read_csv('your_data.csv')  # Example to load a DataFrame

# Create an imputer object with a mean filling strategy
imputer = SimpleImputer(strategy='mean')

# Apply the imputer to our data frame
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [ ]:
tabular_data = df_imputed

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, brier_score_loss
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

# Load your data (replace 'actual_graph_22_16features.csv' and 'actual_table_22_16features.csv' with your actual data file paths)
graph_data = pd.read_csv('/content/drive/MyDrive/CARS/tensor.csv')
#tabular_data = pd.read_csv('actual_table_22_16features.csv')

X_graph = graph_data.iloc[:, :-1].values
y_graph = graph_data['trojan'].values

X_tabular = tabular_data.iloc[:, :-1].values
y_tabular = tabular_data['trojan'].values

# Reshape X_graph to have 3 dimensions (batch size, sequence length, input dimension)
X_graph = X_graph.reshape(X_graph.shape[0], X_graph.shape[1], 1)

# Split the data into training and testing sets
X_graph_train, X_graph_test, y_graph_train, y_graph_test = train_test_split(X_graph, y_graph, test_size=0.2, random_state=42)
X_tabular_train, X_tabular_test, y_tabular_train, y_tabular_test = train_test_split(X_tabular, y_tabular, test_size=0.2, random_state=42)

# Modify your create_graph_model and create_tabular_model functions for multi-class classification
def create_graph_model(input_shape, num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=input_shape),
        tf.keras.layers.MaxPooling1D(pool_size=2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(num_classes, activation='softmax')  # 'num_classes' is the number of classes in your multi-class problem
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def create_tabular_model(input_shape, num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(64, activation='relu', input_shape=input_shape),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(num_classes, activation='softmax')  # 'num_classes' is the number of classes in your multi-class problem
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Assuming you have 'num_classes' classes in your multi-class problem
num_classes = 3  # Replace with the actual number of classes in your dataset

# Train your graph model and tabular model (replace with your actual training code)

graph_model = create_graph_model(X_graph_train.shape[1:], num_classes)
graph_model.fit(X_graph_train, to_categorical(y_graph_train, num_classes=num_classes), epochs=20, batch_size=5, verbose=1)

tabular_model = create_tabular_model(X_tabular_train.shape[1:], num_classes)
tabular_model.fit(X_tabular_train, to_categorical(y_tabular_train, num_classes=num_classes), epochs=20, batch_size=5, verbose=1)

# Predictions from both models
graph_predictions = graph_model.predict(X_graph_test)
tabular_predictions = tabular_model.predict(X_tabular_test)

# Combine predictions using averaging (you can adjust this method as needed)
combined_predictions = (graph_predictions + tabular_predictions) / 2

# Convert combined predictions to class labels by selecting the class with the highest probability
combined_predictions_classes = np.argmax(combined_predictions, axis=1)

# Calculate accuracy, confusion matrix, classification report, and Brier score for multi-class classification
accuracy = accuracy_score(y_graph_test, combined_predictions_classes)
confusion = confusion_matrix(y_graph_test, combined_predictions_classes)
classification_rep = classification_report(y_graph_test, combined_predictions_classes)

# Calculate the Brier score
y_true_one_hot = to_categorical(y_graph_test, num_classes=num_classes)

print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification_rep}')


Epoch 1/20
1568/1568 [==============================] - 11s 7ms/step - loss: 3.6517 - accuracy: 0.8649
Epoch 2/20
1568/1568 [==============================] - 9s 5ms/step - loss: 0.4797 - accuracy: 0.8821
Epoch 3/20
1568/1568 [==============================] - 4s 3ms/step - loss: 0.4456 - accuracy: 0.8827
Epoch 4/20
1568/1568 [==============================] - 6s 4ms/step - loss: 0.4474 - accuracy: 0.8825
Epoch 5/20
1568/1568 [==============================] - 4s 3ms/step - loss: 0.4504 - accuracy: 0.8824
Epoch 6/20
1568/1568 [==============================] - 4s 3ms/step - loss: 0.4429 - accuracy: 0.8827
Epoch 7/20
1568/1568 [==============================] - 5s 3ms/step - loss: 0.4424 - accuracy: 0.8827
Epoch 8/20
1568/1568 [==============================] - 5s 3ms/step - loss: 0.4533 - accuracy: 0.8820
Epoch 9/20
1568/1568 [==============================] - 4s 3ms/step - loss: 0.4454 - accuracy: 0.8827
Epoch 10/20
1568/1568 [==============================] - 4s 3ms/step - loss: 0.44

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Predictions from the model
graph_predictions = graph_model.predict(X_graph_test)

# Convert predictions to class labels by selecting the class with the highest probability
graph_predictions_classes = np.argmax(graph_predictions, axis=1)

# Calculate accuracy, confusion matrix, classification report, and Brier score for multi-class classification
accuracy = accuracy_score(y_graph_test, graph_predictions_classes)
confusion = confusion_matrix(y_graph_test, graph_predictions_classes)
classification_rep = classification_report(y_graph_test, graph_predictions_classes)


print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification_rep}')

62/62 [==============================] - 0s 3ms/step
Accuracy: 88.06%
Confusion Matrix:
[[1726    0    0]
 [ 132    0    0]
 [ 102    0    0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.94      1726
           1       0.00      0.00      0.00       132
           2       0.00      0.00      0.00       102

    accuracy                           0.88      1960
   macro avg       0.29      0.33      0.31      1960
weighted avg       0.78      0.88      0.82      1960



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import brier_score_loss
from keras.utils import to_categorical

# Assuming 'y_graph_test' contains class labels (e.g., 0, 1, 2, ...) for multi-class classification
# Calculate the true class probabilities as one-hot encoded labels
y_true_one_hot = to_categorical(y_graph_test, num_classes=3)

# Predict class probabilities using your trained model
y_pred_probabilities = graph_model.predict(X_graph_test)

# Calculate the Brier score for each class
brier_scores = []

for class_idx in range(3):  # Assuming you have 3 classes
    class_true_probs = y_true_one_hot[:, class_idx]
    class_pred_probs = y_pred_probabilities[:, class_idx]
    class_brier_score = brier_score_loss(class_true_probs, class_pred_probs)
    brier_scores.append(class_brier_score)

print(f'Brier Scores for Each Class:')
for class_idx, score in enumerate(brier_scores):
    print(f'Class {class_idx}: {score:.4f}')

62/62 [==============================] - 0s 3ms/step
Brier Scores for Each Class:
Class 0: 0.1052
Class 1: 0.0629
Class 2: 0.0493
